apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  namespace: demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    app: web-app
