apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          volumeMounts:
            - name: html-files
              mountPath: /usr/share/nginx/html
        - name: app
          image: python:3.9-slim
          command: ["python", "-u", "/app/app.py"]
          volumeMounts:
            - name: app-scripts
              mountPath: /app
      volumes:
        - name: html-files
          configMap:
            name: app-config
        - name: app-scripts
          configMap:
            name: app-config
