apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: demo
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ=   # 'password' base64 encoded
  mysql-user: dXNlcg==               # 'user' base64 encoded
  mysql-password: cGFzcw==           # 'pass' base64 encoded
