apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: clase8
  labels:
    app: php-apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache-container
        image: php:7.4-apache
        ports:
        - containerPort: 80
        volumeMounts:
        - name: php-config
          mountPath: /var/www/html/index.php
          subPath: index.php
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-database
      volumes:
      - name: php-config
        configMap:
          name: php-index-configmap
